sudo: false
language: node_js
node_js:
  - 'node'
env:
  global:
  - NODE_ENV=production
  - NPM_TAG=latest
  - RELEASE_VERSION="0.0.$(date +'%Y%m%d%H%M%S')"
before_deploy:
- >
  if [ -z "$BEFORE_DEPLOY_RAN" ]; then
    npm --no-git-tag-version version $RELEASE_VERSION
    if [ "$TRAVIS_BRANCH" == "master" ]; then export NPM_TAG=stable; fi
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    export BEFORE_DEPLOY_RAN=true
  fi
deploy:
- provider: npm
  on:
    branch:
    - master
    condition: $TRAVIS_EVENT_TYPE != cron
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  tag: $NPM_TAG
